name: bnb
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Base
  - python
  - pytorch=>2.1
  - pytorch-cuda=11.8
  - cuda=11.8
  # Libraries
  - accelerate
  - einops
  - scipy
  - transformers
  # Development
  - pytest
  - pytest-cases # more readable and composable parametrized tests
  - ipython      # better interactive shell
  - debugpy      # debugger-support for VSCode
  - yapf         # code formatting
  - monkeytype   # infer type annotations
  - rich         # better, colored tracebacks, etc
  - pytest-sugar # better pytest output
