# for cmake build
name: bnb
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python
  - accelerate
  - scipy
  - transformers
  - pytest
  - pytest-cases
  - ipython
  - debugpy
  - yapf
  - monkeytype
  - rich
  - pytest-sugar
